name: k-means-environment
channels:
  - conda-forge
dependencies:
  - python
  - numpy
  - pandas
  - matplotlib
  - seaborn
  - scikit-learn
  - pip
  - pip:
      - nbgitpuller
      - sphinx-gallery
